<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <!-- Worker SDK adds IHostedService plumbing. RootNamespace is the only property
         not already in Directory.Build.props that needs to be here. -->
    <RootNamespace>Jacobian.Hl7Integration.Worker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jacobian.Hl7Integration.Domain\Jacobian.Hl7Integration.Domain.csproj" />
    <ProjectReference Include="..\Jacobian.Hl7Integration.Parser\Jacobian.Hl7Integration.Parser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
